### PR TITLE
Add a link to the AUR package

### PR DESCRIPTION
**Pull request by christian-heusel**
This add a link to the AUR package of `flemozi` to the `README.md` :+1:

### CODE REVIEW

**Comment by christian-heusel** [comment]
Regarding the PKGBUILD there is quite some room for improvements. i.e. the following line is rather sketchy:
https://github.com/christian-heusel/aur/blob/251d67555332d5bff77ea382d194f220688cb86f/flemozi/PKGBUILD#L23

Could you fix the need for the env file and solve it via cmd parameters? 😄 
Also let me know if you have other suggestions!

**Comment by KRTirtho** [comment]
Flemozi needs a Giphy and a Tenor API key to enable GIF (JIF not GIF :upside_down_face: ) support. Building it from source requires `TENOR_API_KEY` & `GIPHY_API_KEY` to be available. We can theoretically just pass `TENOR_API_KEY` & `GIPHY_API_KEY` as env vars when running the app or add these to `.bashrc` or `.zshrc`

**Comment by KRTirtho** [comment]
But in future I'll add an option to override and store these credentials in flemozi

**Comment by KRTirtho** [comment]
Btw, flemozi needs [libkeybinder3](https://archlinux.org/packages/extra/x86_64/libkeybinder3/) maybe? This is a required dependency for non-wayland systems

**Comment by christian-heusel** [comment]
> Btw, flemozi needs [libkeybinder3](https://archlinux.org/packages/extra/x86_64/libkeybinder3/) maybe? This is a required dependency for non-wayland systems

Yes libkeybinder and the flutter deps are currently missing, I will improve that today:
https://github.com/christian-heusel/aur/issues/1

**Comment by KRTirtho** [comment]
I'm merging this for now. We'll track the aur issues in your repo

**Pull request merged**
